media:
  input: src/media
  output: /src/media
content:
  - name: posts
    label: Posts
    path: src/_posts
    type: collection
    fields: [ title, published, "tags[0]", author.name ]
      
  - name: authors
    label: Authors
    path: src/_data/authors.json
    type: file
    fields: [ title, published, "tags[0]", author.name ]
      
view:
  fields: [ title, date, published ] # title is the first entry and thus will be set to primary
  sort: [ date, title, published ]
  default:
    search: 'author:Patricia'
    sort: date
    sort: desc
